networks:
  traefik_proxy:
    name: "${TRAEFIK_PROXY_NETWORK_NAME:-traefik-proxy}"
    external: true

volumes:
  traefik_acme: {}

services:
  traefik:
    image: traefik:v2.11
    hostname: "traefik"
    container_name: "traefik"
    restart: always
    networks:
      traefik_proxy: {}
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    command:
      - "--global.checknewversion=false"
      - "--global.sendAnonymousUsage=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=${TRAEFIK_PROXY_NETWORK_NAME:-traefik-proxy}"
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.le.acme.email=${TRAEFIK_LE_MAIL:-myemail@example.com}"
      - "--certificatesresolvers.le.acme.storage=/acme/acme.json"
#      - "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.le.acme.tlschallenge=${TRAEFIK_LE_TLS_CHALLENGE:-false}"
      - "--certificatesresolvers.le.acme.keytype=RSA4096"
      - "--api=true"
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--log.level=INFO"
      - "--accessLog=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=le"
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_MAIN_DOMAIN:-localhost}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.priority=25"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"
      - "traefik.http.middlewares.dashboard-auth.digestauth.users=${TRAEFIK_DIGESTAUTH_USERS:-admin:traefik:817374111f31cc282162486425ee5e9e}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik_acme:/acme:rw"
      - "./dynamic_conf:/etc/traefik/dynamic_conf:ro"
    environment:
      TZ: "${TZ:-Europe/Warsaw}"
