version: '3'

networks:
  traefik-proxy:
    external: true

services:
  traefik:
    image: traefik:v2.10
    hostname: traefik
    restart: always
    networks:
      traefik-proxy: {}
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    command:
      - --global.checknewversion=false
      - --global.sendAnonymousUsage=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik-proxy
      - --providers.file.directory=/etc/traefik/dynamic_conf
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.le.acme.email=myemail@example.com
      - --certificatesresolvers.le.acme.storage=/acme/acme.json
      - --certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.le.org/directory
      - --certificatesresolvers.le.acme.tlschallenge=false
      - --certificatesresolvers.le.acme.keytype=RSA4096
      - --api=true
      - --api.insecure=false
      - --api.dashboard=true
      - --log.level=INFO
      - --accessLog=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=le"
      - "traefik.http.routers.dashboard.rule=Host(`localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.priority=25"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"
      - "traefik.http.middlewares.dashboard-auth.digestauth.users=admin:traefik:817374111f31cc282162486425ee5e9e"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme:/acme:rw
      - ./dynamic_conf:/etc/traefik/dynamic_conf:ro
    environment:
      TZ: Europe/Warsaw
